// Auto-generated by `wrangler cf-typegen` — do not edit manually.
// Re-run after changing wrangler.jsonc bindings.

interface Env {
  // Durable Object — one instance per agent session
  MCP_AGENT: DurableObjectNamespace;

  DASHBOARD_BROADCASTER: DurableObjectNamespace;

  // KV — shared context readable by all agents
  SHARED_CONTEXT: KVNamespace;

  // Vars
  ENVIRONMENT: string;
  PROJECT_NAME: string;
  DASHBOARD_ORIGIN: string;

  // Secrets (set via: wrangler secret put SECRET_NAME)
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  AUTH_SECRET: string; // random 32-char string for signing session tokens
}
